In [ ]:
# coding=utf-8
'''
建立一個外觀 (9, 9) 的 ndarray 並且填入九九乘法表
Author: Youngmi
'''

In [1]:
import numpy as np

In [16]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
arr11 = np.ones((1,9))
arr2 = 2 *np.ones((1,9))
arr3 = 3 *np.ones((1,9))
arr4 = 4 *np.ones((1,9))
arr5 = 5 *np.ones((1,9))
arr6 = 6 *np.ones((1,9))
arr7 = 7 *np.ones((1,9))
arr8 = 8 *np.ones((1,9))
arr9 = 9 *np.ones((1,9))

In [63]:
temp = np.concatenate((arr11,arr2,arr3,arr4,arr5,arr6,arr7,arr8,arr9),axis=0)
temp

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.],
       [ 8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.],
       [ 9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.]])

In [65]:
result = arr1 * temp
result

array([[  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.],
       [  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.],
       [  3.,   6.,   9.,  12.,  15.,  18.,  21.,  24.,  27.],
       [  4.,   8.,  12.,  16.,  20.,  24.,  28.,  32.,  36.],
       [  5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.],
       [  6.,  12.,  18.,  24.,  30.,  36.,  42.,  48.,  54.],
       [  7.,  14.,  21.,  28.,  35.,  42.,  49.,  56.,  63.],
       [  8.,  16.,  24.,  32.,  40.,  48.,  56.,  64.,  72.],
       [  9.,  18.,  27.,  36.,  45.,  54.,  63.,  72.,  81.]])